# 스테이징 1
FROM node:22-alpine AS builder

WORKDIR /var/web05-Denamu/server

COPY ../package*.json ./

COPY ../src ./

COPY ../tsconfig.json .

RUN npm ci

RUN npm run build

# 실행 빌드
FROM node:22-alpine

WORKDIR /var/web05-Denamu/server

COPY --from=builder /var/web05-Denamu/server/dist ./dist

COPY --from=builder /var/web05-Denamu/server/node_modules ./node_modules

CMD ["npm","start"]