FROM node:22.11.0-alpine AS builder

WORKDIR /var/web05-Denamu/client

COPY .. .

RUN npm ci

RUN npm run build

FROM nginx:1.18.0-alpine

WORKDIR /var/web05-Denamu/client

COPY --from=builder /var/web05-Denamu/client/dist /var/web05-Denamu/client/dist
COPY ../../static /var/web05-Denamu/static

CMD ["nginx","-g","daemon off;"]