FROM nginx:1.18.0

WORKDIR /var/web05-Denamu/client

COPY ../../nginx/scripts /etc/nginx/scripts
COPY ../../nginx/nginx.conf /etc/nginx/nginx.conf

RUN sh "/etc/nginx/scripts/generate_cert.sh"

CMD ["nginx","-g","daemon off;"]