name: Feed-Crawler-Deployment

on:
  push:
    branches:
      - main
    paths:
      - "feed-crawler/**"
  workflow_dispatch: # 수동 실행을 허용하는 이벤트

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      # public 서버로 ssh 접속
      - name: ssh connection
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.CLOUD_PUBLIC_INSTANCE_HOST }}
          username: ${{ secrets.CLOUD_PUBLIC_INSTANCE_USERNAME }}
          key: ${{ secrets.CLOUD_PUBLIC_INSTANCE_SSH_KEY }}
          port: ${{ secrets.CLOUD_PUBLIC_INSTANCE_PORT }}
          # 1.nvm 설정
          # 2.private 서버로 접속을 위한 ssh key 생성
          # 3. 깃헙 소스코드 업데이트
          # 4. 환경변수 설정
          # 5. 내부망으로의 전달을 위한 의존성 설치 & 압축 & 전달
          # 6. private 서버로 접속 후 압축 해제 & 기존 버전 제거 & 새 버전 적용 & 빌드 & 실행 (Heredoc 을 사용해 라인 구분)
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            set -e
            echo "${{ secrets.CLOUD_PRIVATE_INSTANCE_SSH_KEY }}" > /tmp/private_key
            chmod 600 /tmp/private_key

            cd /var/web05-Denamu
            git pull origin main
            cd /var/web05-Denamu/feed-crawler/

            echo "DB_PORT=${{ secrets.FEED_CRAWLER_DB_PORT }}" > .env
            echo "DB_HOST=${{ secrets.FEED_CRAWLER_DB_HOST }}" >> .env
            echo "DB_NAME=${{ secrets.FEED_CRAWLER_DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.FEED_CRAWLER_DB_USER }}" >> .env
            echo "DB_PASS=${{ secrets.FEED_CRAWLER_DB_PASSWORD }}" >> .env
            echo "TIME_INTERVAL=${{ vars.FEED_CRAWLER_TIME_INTERVAL }}" >> .env
            echo "TEST_TIME_INTERVAL=${{ vars.FEED_CRAWLER_TEST_TIME_INTERVAL }}" >> .env
            echo "REDIS_HOST=${{secrets.REDIS_HOST }}" >> .env
            echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> .env
            echo "REDIS_USERNAME=${{secrets.REDIS_USERNAME}}" >> .env
            echo "REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}" >> .env
            echo "AI_API_KEY=${{secrets.AI_API_KEY}}" >> .env
            echo "AI_RATE_LIMIT_COUNT=${{ secrets.AI_RATE_LIMIT_COUNT }}" >> .env

            npm ci
            cd /var/web05-Denamu
            tar -czvf /tmp/app_feed_crawler.tar.gz feed-crawler
            scp -i /tmp/private_key /tmp/app_feed_crawler.tar.gz root@172.16.0.22:/tmp/app_feed_crawler.tar.gz
                           
            ssh -i /tmp/private_key ${{ secrets.CLOUD_PRIVATE_INSTANCE_USERNAME }}@${{ secrets.CLOUD_PRIVATE_INSTANCE_HOST }} << 'EOF'

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22

            cd /var/web05-Denamu
            pm2 delete all

            cd /tmp
            tar -xzvf app_feed_crawler.tar.gz
            rm -rf /var/web05-Denamu/feed-crawler
            mv /tmp/feed-crawler /var/web05-Denamu

            cd /var/web05-Denamu/feed-crawler
            npm run build
            cd /var/web05-Denamu

            pm2 start ecosystem.config.js
            EOF
